- src/components/checkbox/checkbox.ts
- src/components/components.ts
- src/components/index.ts
- src/components/selectboxes/selectboxes.spec.ts
- src/components/selectboxes/selectboxes.ts
- src/fixtures/forms/kitchensink.ts
- src/templates/bootstrap.ts
- src/templates/bootstrap/components/selectboxes.html
Implementation of SelectBox component.
Added required template and typescript code to render selectbox component.
Test formio component for select box.
Its type should be selectboxes.
Should allow label.
Should allow custom class.
Should allow select box component with required.
Check select box option values are available or not.
Check select box options contains labels or not.
Check select boxes appears in inline or not.
> Selectbox component

- src/components/address/address.spec.ts
- src/components/address/address.ts
- src/components/components.ts
- src/components/index.ts
- src/fixtures/forms/kitchensink.ts
- src/templates/bootstrap.ts
- src/templates/bootstrap/components/address.html
Added required template and typescript code to render address component.
Used ng2-select library to implement address component.
Test formio component for address.
Its type should be address.
Should allow label value.
Should allow placeholder.
Should allow custom class.
> Implementation of address component.

- package.json
The version should be 0.7.4:
https://angular.io/docs/js/latest/quickstart.html
```json
"rxjs": "5.0.1",
"zone.js": "^0.7.4"
```
Otherwise it spills errors when installing locally.
Thanks!
> Fix zone.js version dependency for NG 2.4

- src/formio-component.component.ts
This is causing an issue when attempting to use customer conditional logic. Users are told they have the data object available to them as a variable named "data", but that data isn't being passed into the conditional check and is causing warnings/errors, and improperly showing elements.
https://github.com/formio/formio-utils/blob/master/src/index.js
I'm not sure the proposed change is correct, but I wanted to draw the issue to your attention.
> Entire data set not being passed to CheckCondition method.

- package.json
`npm test` returns an error when `@types/jasmine` version > 2.5.41
webpack: Compiled successfully.
webpack: Compiling...
ERROR in [default] /home/gsm/Desktop/form.io/ng2-formio/node_modules/@types/jasmine/index.d.ts:39:37 
A parameter initializer is only allowed in a function or constructor implementation.
ERROR in [default] /home/gsm/Desktop/form.io/ng2-formio/node_modules/@types/jasmine/index.d.ts:39:45 
Cannot find name 'keyof'.
ERROR in [default] /home/gsm/Desktop/form.io/ng2-formio/node_modules/@types/jasmine/index.d.ts:39:51 
'=' expected.
ERROR in [default] /home/gsm/Desktop/form.io/ng2-formio/node_modules/@types/jasmine/index.d.ts:41:45 
A parameter initializer is only allowed in a function or constructor implementation.
ERROR in [default] …
> Fix version @types/jasmine to fix compiling error

- src/formio.common.ts
- src/formio.component.ts
Angular 4 Render now has a variable defined in the src/formio.component.ts under this.options that allows users to turn on and off form submission alerts for their project.
> Added DisableAlerts Feature

- src/components/formio/formio.component.ts
Add a for each in a validation message to get the Error message from details property.
Unique Validations doesn't have message property. The message property is in details array on the error instance.
> (FIX): Unique Validation Error on Alerts

- src/components/formio/formio.component.ts
IF conditional doesn't check for the error.message property.
> (Fix): Conditionals in Error Alerts

- src/grid/grid.component.ts
Pull request for issue #270.
Fixes JavaScript error when using `<formio-grid createText="...">`.
> Skip early attempts to set grid footer createText.

- src/grid/grid.component.ts
When I made a query filtering the forms and there were more than one page, the query was lost when I changed the page.
> Fixing search query being lost after page change

- src/FormioBaseComponent.ts
Avoid error message when currentValue is undefined.
I had to edit this manually, because I could not build with npm:build without thousands of peer dependency errors (No name was provided for external module).
Any link how to build the package would be helpful.
> Tested changes.hideComponents.currentValue

- gulpfile.js
- package-lock.json
- package.json
- src/FormioBaseComponent.ts
- src/components/formbuilder/formbuilder.component.ts
- src/components/formio/formio.component.ts
- src/custom-component/create-custom-component.ts
- src/custom-component/custom-tags.service.ts
- src/custom-component/register-custom-component.ts
- src/formio.common.ts
- src/formio.service.ts
- src/index.ts
Helper classes to create and register custom fields based on any Angular component implemented as field input (with `value` Input and `valueChange` Output).
It creates a webcomponent (Angular Element), then creates a custom field class using that webcomponent as the input element.
Usage example:
```
import { Injector } from '@angular/core';
import { FormioCustomComponentInfo, registerCustomFormioComponent } from 'angular-formio';
import { DatepickerComponent } from './datepicker.component';
import { datePickerEditForm } from './edit-form';
const COMPONENT_OPTIONS: FormioCustomComponentInfo = {
type: 'mydatepicker',
selector: 'my-datepicker',
title: 'Datepicker',
group: 'basic',
icon: 'fa fa-calendar',
editForm: datePickerEditForm,
};
export function registerDatepickerComponent(injector: …
```
> Custom Angular fields

- src/FormioBaseComponent.ts
- src/components/formbuilder/formbuilder.component.ts
- src/components/formio/formio.component.html
- src/components/formio/formio.component.ts
- src/components/loader/formio.loader.ts
Angular runs inside NgZone which counts the microtasks and runs change detection when needed. However the external JavaScript libs should run outside of the zone not to give extra work to Angular.
https://angular.io/api/core/NgZone
This PR adds abilities to run formio outside of the zone and run the events back in the zone.
Breaking Changes:
- `NgZone` service is required for the components.
- The `FormioLoader` service is updated. The `loading` flag is also available as Observable, so we can use the `async` pipe in the template which takes care of the change detection properly.
> Performance: Run formio outside of ngZone

- gulpfile.js
fix gulpfile configuration to work correctly with gulp-better-rollup - it uses gulp.src rather than input param https://www.npmjs.com/package/gulp-better-rollup
Resolves #392
> fix gulpfile rollup configuration

- src/custom-component/create-custom-component.ts
- src/formio.common.ts
Add an option to use the field options inside custom components.
Usage:
`fieldOptions: ['myOption']`
Example:
```js
const COMPONENT_OPTIONS: FormioCustomComponentInfo = {
type: 'radiobuttons',
selector: 'radio-buttons',
title: 'Radio Buttons',
group: 'basic', 
icon: 'fa fa-star', 
fieldOptions: ['values'],
editForm: RadioButtonsForm,
}
```
Closes https://github.com/formio/angular-formio/issues/409
> Explicit field options for custom components

- src/custom-component/create-custom-component.ts
- src/formio.common.ts
**This connects the emit event functionality with an Angular component.**
Inside the Custom Angular Component, implement as the following:
```
@Output()
formioEvent = new EventEmitter<FormioEvent>();
```
And emit an event like:
```
this.formioEvent.emit({ eventName: 'submitButton', data: { state: 'submitted' } });
```
This will use the formio emit functionality like:
```
this.emit('submitButton', {
state: 'submitted',
component: this.component
});
```
The code behind it looks like:
```
this._customAngularElement.addEventListener('formioEvent', (event: CustomEvent<FormioEvent>) => {
this.emit(event.detail.eventName, {
...event.detail.data,
component: this.component
});
});
```
Note: the formio component class behind the Custom Component is automatically attached.
Closes #434
> Support emit event from Custom Component

- src/FormioBaseComponent.ts
- src/package-lock.json
Since 'modified' is not a flag, but a parameter which is passed to the onChange(), in the angular 'change' event we don't have it and have no way to determine if it was a user-triggered event or an internal one.
> Added "modified" variable to the angular "change" event

- projects/angular-formio/src/index.ts
In some projects, we need to customize the Formio based on our needs, so, services like components should be exported in order to use in other places. As you know, this service can be injected into the `FormioComponent` component (projects/angular-formio/src/components/formio/formio.component.ts).
In this PR, this service is exported, so, we are able to use this service from the outer of this package.
Issue: #877
> Exporting the custom-tag-service.ts service.

- projects/angular-formio/grid/src/form/FormGridBody.component.html
https://formio.atlassian.net/browse/FIO-7232
*The permission button was removed from FormGridBody, for a grid with gridType form, because there is no corresponding route for the permissions path. For the Formmanager application, the permissions button was added by changing the template for FormGridBody*
*https://github.com/formio/formmanager/pull/172*
> FIO-7232 removed permissions button from FormGridBody

- projects/angular-formio/manager/src/form-manager.service.ts
Fixed general access to manager.
Form manager services was looking for formbuilder and formadmin roles that sometimes won't exist in the formio project causing a undefined reading _id. 
This error was blocking the feature to work correctly.
> Fixing General access to Manager using formadmin formbuilder roles

- projects/angular-formio/src/components/formioreport/formioreport.component.ts
https://formio.atlassian.net/browse/FIO-8004
Previously, every form that is loaded in formio/angular was using a setForm function, that handles loading functionality through a idLoading flag. Reports are loaded a bit differently than other forms, and isLoading flag never resets in that case, that's why the code to reset that flag was added explicitly to the functions that set up reports
> FIO-8004 Fixed loader incorrectly showing in embed reports

- package.json
In the latest stable version of `@formio/angular` 7.0.0 we have a hard dependency on `formiojs` styles here:
https://github.com/formio/angular/blob/v7.0.0/projects/angular-formio/src/components/formio/formio.component.ts#L11
It means that it doesn't matter which `formiojs` version I will use as a peer dependency in my project I will still get a styles from a version specified in your repository and they will be inlined in the `FormioComponent` during build time.
https://github.com/formio/formio.js/pull/5447
I have this issue in my project and the long-term fix could probably be a separate loading of styles and not inlining them but so far package update may also work fine (as the local style override...but override does not look like the best solution).
> Update formiojs version to 4.19.0

- projects/angular-formio/auth/src/auth.service.ts
Changed the JSON key from register to resetpass
FormioAuthService class was using the incorrect key for setting `public resetPassForm: String`
This fix will allow the instance variable to be set to the correct form
> Changed resetPassForm to use resetpass key instead of register key

- projects/angular-formio/src/FormioBaseComponent.ts
https://formio.atlassian.net/browse/FIO-8915
Before, in formiojs 4x branch, the showErrors method could accept a single error and add it to all form errors (this.errors). When the error is undefined, this method showed all other form errors any way. In formiojs 5.x this method expects the list of errors, if errors are empty, the method just removes the errors list. So, this PR changed the showErrors to call it with errors argument.
Manually
> FIO-8915: fixed an issue where errors list does not display in formmanager and formview pro

- projects/angular-formio/manager/src/index/index.component.ts
https://formio.atlassian.net/browse/FIO-8819
**Issue**: The formManager search calls `this.formGrid.pageChanged`, which internally calls the `refreshGrid` method. The `refreshGrid` method makes an HTTP request to get forms. Additionally, the formManager search also calls `this.formGrid.refreshGrid`. This results in two `refreshGrid` calls and two HTTP requests with the same data. Furthermore, the variables `this.gridQuery` and `this.formGrid.query` are equal because `this.gridQuery` is passed as a prop to `this.formGrid`.
Regarding the clearSearch method: when we manually reassign `this.gridQuery` to another object, `this.gridQuery` and `this.formGrid.query` are no longer equal, so we need to reassign `this.formGrid.query` before making the API call.
**Solution**: Remove the second …
> FIO-8819: Removed duplicate request on form manager search

- projects/angular-formio/src/FormioBaseComponent.ts
https://formio.atlassian.net/browse/FIO-8993
**Issue**: The `message` variable can be either a single string or an array of strings. When `message` is a single string, using `message[0]` incorrectly accesses the first character of the string instead of the intended first element of an array.
**Solution**: Add a check to determine if `message` is an array or a single string before accessing its elements.
> FIO-8993: Fixed component validation message

- projects/angular-formio/embed/src/builder.component.ts
- projects/angular-formio/embed/src/formio.component.ts
- projects/angular-formio/src/FormioBaseComponent.ts
- projects/angular-formio/src/components/formbuilder/formbuilder.component.ts
- projects/angular-formio/src/formio.common.ts
https://formio.atlassian.net/browse/FIO-9258
Gave the angular formio component options the webform options type along with extending the specific angular webform options as well. Also fixed some eslint errors
Give correct type definitions to formio
N/A
N/A
Manually tested
> FIO-9258: separated webform options from angular webform options, fix some eslint errors, fix form options type

- projects/angular-formio/package.json
*Updated `ngx-bootstrap` version so it's compatible with the newest version of Angular 16.*
> Update ngx-bootstrap version for compatibility with Angular 16
