src/components/components.ts
src/components/index.ts
src/components/table/table.spec.ts
src/components/table/table.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/table.html

Added required template and typescript code to render table component.
Test formio component for Table.
Should allow table classes like table-bordered, table-condensed, table-hover, table-striped,etc.
Should allow numRows and numCols of table.
Should allow components inside table.

Implementation of Table component.

---

src/components/components.ts
src/components/index.ts
src/components/panel/panel.spec.ts
src/components/panel/panel.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/panel.html

Added required template and typescript code to render panel component.
Test formio component for panel.
It should contain components.
It should create panel control.
Should allow different theme values.
Should allow title value.
Its type should be panel.

Implementation of Panel component.

---

src/components/components.ts
src/components/fieldset/fieldset.spec.ts
src/components/fieldset/fieldset.ts
src/components/index.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/fieldset.html

Added required template and typescript code to render the fieldset component.
Test formio component for FieldSet.
It should allow legend value.
Its type should be fieldset.
Should create the fieldset control.
It should contains components.

Implementation of fieldset component.

---

src/components/components.ts
src/components/index.ts
src/components/well/well.spec.ts
src/components/well/well.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/well.html

Added required template and typescript code to render well component.
Test formio component for well.
Its type should be well.
It should contain components.
It should create well control.

Implementation of Well component.

---

src/components/components.ts
src/components/htmlelement/htmlelement .spec.ts
src/components/htmlelement/htmlelement.ts
src/components/index.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/htmlelement.html

Implementation of Html Element component.
Added required template and typescript code to render html element component.
Test formio component for html element.
Its type should be html element.
Should allow class name.
Should allow tag.
Should allow content.
Should allow attributes.

Implementation of Html Element component.

---

src/components/components.ts
src/components/content/content.spec.ts
src/components/content/content.ts
src/components/index.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/content.html

Added required template and typescript code to render content component.
Test formio component for content.
Its type should be content.
Should allow key value.
Should allow html to render.

Implementation of Content component.

---

src/components/components.ts
src/components/currency/currency.spec.ts
src/components/currency/currency.ts
src/components/index.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/currency.html

Implementation of currency component.
Merged master with currency-component branch.

Currency component

---

src/components/components.ts
src/components/index.ts
src/components/survey/survey.spec.ts
src/components/survey/survey.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/survey.html

Implementation of Survey component.
Added required template and typescript code to render survey component.
Test formio component for survey.
Its type should be survey.
Should allow label value.
Should allow required.
Check for values are available or not.
Check for survey values contains label or not.
Check for questions are available or not.

Implementation of Survey component.

---

package.json
src/components/components.ts
src/components/datetime/datetime.ts
src/components/index.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap.ts
src/templates/bootstrap/components/datetime.html

Implementation of datetime component.
Added the ng2-bootstrap library to include datepicker and timepicker.
Implemented test cases for datetime component.
Test formio component for Datetime.
Its type should be Datetime.
Should allow label value. 
Should allow placeholder.
Should allow minDate, maxDate, format.
Should allow Datepicker options.
Should allow timepicker options.

Datetime component

---

src/components/survey/survey.ts
src/fixtures/forms/kitchensink.ts
src/templates/bootstrap/components/survey.html

Implementation of binding survey component data to submissions.
Added the functionality to submit the survey component data in object format.

Implementation of binding survey component data to submissions.

---

src/formio.alerts.component.ts
src/grid/grid.component.ts

fix(FOR-1014): Alerts is crashing on Submission Grid in angular-formio

---

package-lock.json
package.json

Closes https://github.com/formio/angular-formio/issues/398

Angular Elements as dependency

---

src/auth/auth.service.ts

Hi Travist & William,
Please accept this pull request. As is for now, the register form is never shown in the formmanager.
Regards,
James

fix to submit to the register form instead of login form

---

src/manager/index/index.component.ts

That was the reason of the bug with red block in formmanager.
My previous changes just showed up the bug, bug the actual reason is that we try to set the first page as the default one but count starts from 0.

Fix(manager): bug with default page number

---

src/grid/GridFooterComponent.ts
src/grid/grid.component.html
src/grid/grid.component.ts
src/grid/submission/SubmissionGridFooter.component.html
src/grid/submission/SubmissionGridFooter.component.ts
src/grid/types/grid-footer-positions.ts

Feat (Grid): added ability to specify footer positions: top, bottom, both

---

src/FormioBaseComponent.ts

Reverts formio/angular-formio#642

Revert "VPAT-664 Replaced angular alerts with renderer ones"

---

projects/angular-formio/src/components/formbuilder/formbuilder.component.ts

@travist Could you pay special attention to the changes? The display mode changes without problems in the select, the updated form is saved correctly, but I could have missed something

FMG-108: remove reloading of PDF form after editing

---

projects/angular-formio/grid/src/form/FormGridFooter.component.html
projects/angular-formio/grid/src/submission/SubmissionGridFooter.component.html
projects/angular-formio/manager/src/form/form.component.html
projects/angular-formio/manager/src/submission/submission/submission.component.html
projects/angular-formio/resource/src/create/create.component.html
projects/angular-formio/resource/src/resource.component.html

`<b>` should not be used. Instead of `<b>` tag in any HTML file, we used use `<strong>` tag. It increases the code quality and follows the coding principles.

FIX BUG: HTML Tag replaced and refactored by corrected ones

---

projects/angular-formio/src/FormioBaseComponent.ts

connected PR: 
https://github.com/formio/grid/pull/12
https://github.com/formio/premium/pull/178

FIO-5128 added support for DT row-based events

---

projects/angular-formio/src/FormioBaseComponent.ts

set renderModeto html when viewOnly flag is set to true

---

projects/angular-formio/src/FormioBaseComponent.ts
projects/angular-formio/src/components/formio/formio.component.html

Currently there is no way to hide the loading spinner

Toggle to hide the loading spinner

---

projects/angular-formio/src/formio.common.ts

fix common ComponentOptions interface for angular 15

---

projects/angular-formio/src/components/formbuilder/formbuilder.component.ts

references to https://github.com/formio/angular/issues/848 and https://github.com/formio/angular/issues/812

Fixed change event undefined on template issue

---

projects/angular-formio/auth/src/auth.service.ts

https://formio.atlassian.net/browse/FIO-6197
We need to send request to api server to invalidate session and then just clear up all data from local storage.
Manual
- [] I have commented my code, particularly in hard-to-understand areas

FIO-6197: fixed issue with valid token after logging off

---

projects/angular-formio/src/FormioBaseComponent.ts
projects/angular-formio/src/components/formioreport/formioreport.component.html
projects/angular-formio/src/components/formioreport/formioreport.component.ts
projects/angular-formio/src/core.ts
projects/angular-formio/src/formio.common.ts
projects/angular-formio/src/formio.module.ts

related PRs:
https://github.com/formio/react/pull/510
https://github.com/formio/ngFormio/pull/715
https://github.com/formio/grid/pull/38
https://github.com/formio/premium/pull/247
https://github.com/formio/formio.js/pull/5081
https://github.com/formio/formio-server/pull/1254
https://github.com/formio/formio/pull/1568
https://github.com/formio/formio-app/pull/1449
https://github.com/formio/keys/pull/1
https://github.com/formio/license/pull/1
https://github.com/formio/reporting/pull/1

FIO-6493: added wrapper for the formio report

---

projects/angular-formio/src/FormioBaseComponent.ts

DataSource Component Blocked by fromSubsmission flag always set to true.

FIO-7611: DataSource not Triggering on change events due to fromSubmission Flag

---

projects/angular-formio/manager/src/edit/edit.component.ts

https://formio.atlassian.net/browse/FIO-8638
*Fixed the behavior in which form components were not saved after changing the form display type*
*n/a*
*n/a*
*locally with using FMG app*

FIO-8638 fixed saving components after changing form display

---

projects/angular-formio/manager/src/submission/submission/submission.component.html

https://formio.atlassian.net/browse/FIO-8667
*The position of the PDF download button has been changed*
*n/a*
*n/a*
*locally*

FIO-8667 fixed location of download PDF button

---

projects/angular-formio/grid/src/form/FormGridFooter.component.html

https://formio.atlassian.net/browse/FIO-8779
*Fixed the position of the page number for FormGrid*
*n/a*
*https://github.com/formio/formmanager/pull/184*
*locally using FMG*

FIO-8779 updated class name for page number

---

README.md

Added compatibility matrix to Angular Version section
N/A
Read me file
*Use this section to provide a summary description of the changes you've made*
N/A
N/A
*Use this section to justify your choices*
N/A
*Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility*
N/A
*Use this section to list any dependent changes/PRs in other Form.io modules*
N/A
N/A
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*

Update README with compatibility matrix.md

---

package.json
projects/angular-formio/package.json

https://formio.atlassian.net/browse/FIO-9324
ngx-bootstrap version to match angular version
In their compatibility [documentation](https://www.npmjs.com/package/ngx-bootstrap) specify the versions needed for each angular version
NA
NA
Manually

FIO-9324: Fixing Dependency to match ngx-bootstrap with Angular versions

---

package.json
projects/angular-formio/embed/src/builder.component.ts
projects/angular-formio/embed/src/formio.component.ts
projects/angular-formio/package.json
projects/angular-formio/src/formio.config.ts
projects/angular-formio/src/formio.utils.ts
yarn.lock

https://formio.atlassian.net/browse/FIO-XXXX
*Use this section to provide a summary description of the changes you've made*
*Use this section to justify your choices*
*Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility*
*Use this section to list any dependent changes/PRs in other Form.io modules*
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*

Expanding the components to allow for more functionality.

---

projects/angular-formio/grid/src/form/FormGridFooter.component.html
projects/angular-formio/manager/src/submission/submission/submission.component.html

https://formio.atlassian.net/browse/FIO-9501
*Updated class names according to bootstrap5*
*n/a*
*https://github.com/formio/formmanager/pull/189*
*https://github.com/formio/formmanager/pull/190*
*locally using formmanager app*

FIO-9501 bootstrap5 updates

---

projects/angular-formio/src/formio.common.ts

Add _id to the formioForm type
forms should have a property of _id on them. This type should reflect that
N/A
N/A
Manually

added _id to formioForm type
